version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: campus-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: campusdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d campusdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
