name: Documentation Link Check

on: 
  pull_request:
    branches: [main]
    paths: 
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      - name: Configure link check
        run: |
          echo "# markdown-link-check configuration\n\n{\n  \"configVersion\": \"1.0\",\n  \"ignorePatterns\": [\n    {\n      \"pattern\": \"^http://localhost\"\n    },\n    {\n      \"pattern\": \"^https://api.adopte1etudiant.com\"\n    },\n    {\n      \"pattern\": \"^https://docs.adopte1etudiant.com\"\n    },\n    {\n      \"pattern\": \"^https://status.adopte1etudiant.com\"\n    }\n  ],\n  \"aliveStatusCodes\": [200, 202, 203, 204, 206, 301, 302, 303, 304, 307, 308]\n}" > .markdown-link-check.json

      - name: Run link check on docs
        run: find docs -name "*.md" -print0 | xargs -0 -n1 markdown-link-check

      - name: Run link check on README.md
        run: markdown-link-check README.md

      - name: Run link check on CHANGELOG.md
        run: markdown-link-check CHANGELOG.md
