name: Secrets scan

on:
  pull_request:
  push:
    branches: [ dev, main ]
    paths:
      - "apps/**"
      - "packages/**"
      - ".env*"
      - "Dockerfile"
      - "docker-compose*.yml"
      - "**/*.ts"
      - "**/*.tsx"

permissions:
  contents: read

jobs:
  trufflehog-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: TruffleHog OSS (repo diff)
        uses: trufflesecurity/trufflehog@v3.90.5
        with:
          extra_args: >-
            --only-verified
            --exclude-paths .trufflehog-exclude.txt
